### ISSUE TITLE
Support for modes

### ISSUE THREAD

**Issue by Unkn0wn-MDCLXIV** [Juerd/eq3-max#2]
Is there a chance that you implement a way to change the mode of the thermostat?

**Comment by Juerd** [comment]
In theory, sure, but setting to "auto" mode is not very useful because this tool doesn't let you configure the timings in the devices.

Instead of using the automatic mode, I suggest keeping the mode at "manual", and using a crontab to configure your heating schedule. Instead of the vacation mode, just do a simple "max set all 15" to set the entire house to 15 degrees (don't forget to temporarily disable the crontab :D).

But if you'd like to submit a patch, I'll definitely consider it.

**Comment by Unkn0wn-MDCLXIV** [comment]
What about Boost?

**Comment by Juerd** [comment]
Boost could be implemented, but until then you can achieve the same by setting the temperature to a high value, waiting 5 minutes, and restoring the temperature to the old value.
