### ISSUE TITLE
Support for the "ECO Button"

### ISSUE THREAD

**Issue by aleritty** [Juerd/eq3-max#5]
I added an ECO Button to the system and I get this error:

```
Use of uninitialized value $setpoint in bitwise and (&) at /opt/eq3-max/bin/../lib/Max.pm line 125, <GEN0> line 9.
Use of uninitialized value $setpoint in bitwise and (&) at /opt/eq3-max/bin/../lib/Max.pm line 126, <GEN0> line 9.
```

I think that error happens because the button doesn't transmit the temperature and all the data, afaik it doesn't transmit at all except a broadcast to "set to eco setpoint".

Maybe I can try to debug it with a little help.
Maybe you can add this feature!

Also thank you for this super useful script!

**Comment by Juerd** [comment]
Aleritty skribis 2018-11-09 10:09 (-0800):
> I added an ECO Button to the system and I get this error:
> ```
> Use of uninitialized value $setpoint in bitwise and (&) at /opt/eq3-max/bin/../lib/Max.pm line 125, <GEN0> line 9.
> Use of uninitialized value $setpoint in bitwise and (&) at /opt/eq3-max/bin/../lib/Max.pm line 126, <GEN0> line 9.
> ```

Unfortunately, because I don't have an eco button, I don't know in which
ways it behaves differently.

Could you add "warn $base64;" after line 118, and send me the base64
data? Maybe I can decode it anyway.

Can't promise anything though :)

> Maybe you can add this feature!

I have no idea how to implement any support for the button. Maybe I can
make the rest work by ignoring the eco button, but actually responding
to a button press is very unlikely to be implemented.

> Also thank you for this super useful script!

You're welcome!
-- 
Met vriendelijke groet, // Kind regards, // Korajn salutojn,

Juerd Waalboer  <juerd@tnx.nl>
TNX

**Comment by Juerd** [comment]
The attempt in 43dafea is incomplete. The "if defined $setpoint" should of course apply to everything using $setpoint, not just the last part.
